apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system #このnamespace名をmetallbのnamespaceと同じにする
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.0.190-192.168.0.200
